export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="clean"

CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"

zstyle ':omz:update' mode disabled

COMPLETION_WAITING_DOTS="false"

HIST_STAMPS="yyyy-mm-dd"

plugins=(
    archlinux
    git
    sudo
    systemd
    z
    zsh-interactive-cd
)

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
